workflows:
    react-native-android:
      name: React Native Android
      environment:
        android_signing:
          - keystore
        vars:
          PACKAGE_NAME: "com.vihat.marketplace.develop"
        groups:
          - google_play
      scripts:
        - name: Install npm dependencies
          script: | 
            git clone git@gitlab.com:vihat_outsource/merchantapp.git
        - name: Install npm dependencies
          script: | 
            npm install
        - name: Set Android SDK location
          script: | 
            echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"
        - name: Set up fastlane, notification, increase build number
          script: |
            sudo gem install fastlane
            gem install bundler
            bundle install
            fastlane increase_build_number_android env:develop
            fastlane start_build_telegram
        - name: Build Android release
          script: | 
            # LATEST_GOOGLE_PLAY_BUILD_NUMBER=$(google-play get-latest-build-number --package-name "$PACKAGE_NAME")
            # if [ -z $LATEST_GOOGLE_PLAY_BUILD_NUMBER ]; then
            #   # fallback in case no build number was found from Google Play.
            #   # Alternatively, you can `exit 1` to fail the build
            #   # BUILD_NUMBER is a Codemagic built-in variable tracking the number
            #   # of times this workflow has been built
            #     UPDATED_BUILD_NUMBER=$BUILD_NUMBER
            # else
            #     UPDATED_BUILD_NUMBER=$(($LATEST_GOOGLE_PLAY_BUILD_NUMBER + 1))
            # fi
            cd android
            ./gradlew assembleDevelopRelease
            cd ..
            fastlane upload_distribution
            fastlane finish_build_telegram
      artifacts:
          - android/app/build/outputs/**/*.apk
    react-native-ios:
        name: React Native iOS
        max_build_duration: 120
        instance_type: mac_mini_m1
        environment:
          ios_signing:
            distribution_type: app_store
            bundle_identifier: "com.vihat.marketplace.develop"
          vars:
            XCODE_WORKSPACE: "sr_marketplace_reactnative.xcworkspace" # <-- Put the name of your Xcode workspace here
            XCODE_SCHEME: "develop" # <-- Put the name of your Xcode scheme here
            APP_ID: 6444644761 # <-- Put the app id number here. This is found in App Store Connect > App > General > App Information
          groups:
            - google_play
          xcode: latest
          cocoapods: default
        scripts:
          - name: Set up fastlane, notification, increase build number
            script: |
              git clone git@gitlab.com:vihat_outsource/merchantapp.git
          - name: Set up code signing settings on Xcode project
            script: xcode-project use-profiles
          - name: Set up fastlane, notification, increase build number
            script: |
              sudo gem install fastlane
              gem install bundler
              bundle install
              fastlane increase_build_number_ios env:develop
              fastlane start_build_telegram
          - name: Install npm dependencies
            script: |
              npm install
          - name: Install CocoaPods dependencies
            script: |
              cd ios && pod install
          - name: Set up code signing settings on Xcode project
            script: |
              xcode-project use-profiles --warn-only
          - name: Build ipa for distribution
            script: |
              xcode-project build-ipa \
                --workspace "$CM_BUILD_DIR/ios/$XCODE_WORKSPACE" \
                --scheme "$XCODE_SCHEME"
              fastlane finish_build_telegram
        artifacts:
          - build/ios/ipa/*.ipa
          - /tmp/xcodebuild_logs/*.log
          - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
          - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
        publishing:
          email:
            recipients:
              - chaunn@vihatgroup.com
            notify:
              success: true
              failure: false
          app_store_connect:
            api_key: $APP_STORE_CONNECT_PRIVATE_KEY 
            key_id: $KEY_ID 
            issuer_id: $ISSUER_ID
            submit_to_testflight: true
            submit_to_app_store: false
