workflows:
    react-native-android:
      name: React Native Android
      environment:
        android_signing:
          - keystore
        groups:
          - google_play
      scripts:
        - name: Get enviroment
          script: | 
            git clone https://oauth2:$GITLAB_TOKEN@gitlab.com/chaunguyen4297/fastlane.git fastlane_clone
            cp -R fastlane_clone/fastlane .
            rm -rf fastlane_clone
            git clone https://oauth2:$GITLAB_TOKEN@gitlab.com/stevenguyen42/srmartketplacekey.git vihatbase_key
            cp -R vihatbase_key/env fastlane 
            cp -R vihatbase_key/file fastlane
            cp -R vihatbase_key/key . 
            rm -rf vihatbase_key
        - name: Install npm dependencies
          script: | 
            npm install
        - name: Set Android SDK location
          script: | 
            echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"
        - name: Set up fastlane, notification, increase build number
          script: |
            sudo gem install fastlane
            gem install bundler
            bundle install
            fastlane increase_build_number_android env:$ENV
            fastlane start_build_telegram env:$ENV
        - name: Build Android release
          script: | 
            # LATEST_GOOGLE_PLAY_BUILD_NUMBER=$(google-play get-latest-build-number --package-name "$APP_ID")
            # if [ -z $LATEST_GOOGLE_PLAY_BUILD_NUMBER ]; then
            #   # fallback in case no build number was found from Google Play.
            #   # Alternatively, you can `exit 1` to fail the build
            #   # BUILD_NUMBER is a Codemagic built-in variable tracking the number
            #   # of times this workflow has been built
            #     UPDATED_BUILD_NUMBER=$BUILD_NUMBER
            # else
            #     UPDATED_BUILD_NUMBER=$(($LATEST_GOOGLE_PLAY_BUILD_NUMBER + 1))
            # fi
            cd android
            ./gradlew $ASSEMPLE
            cd ..
            fastlane upload_distribution env:$ENV
            fastlane finish_build_telegram env:$ENV
      artifacts:
          - android/app/build/outputs/**/*.apk
    react-native-ios:
        name: React Native iOS
        max_build_duration: 120
        instance_type: mac_mini_m1
        environment:
          ios_signing:
            distribution_type: app_store
          groups:
            - google_play
          xcode: latest
          cocoapods: default
        scripts:
          - name: Get enviroment
            script: | 
              git clone https://oauth2:$GITLAB_TOKEN@gitlab.com/chaunguyen4297/fastlane.git fastlane_clone
              cp -R fastlane_clone/fastlane .
              rm -rf fastlane_clone
              git clone https://oauth2:$GITLAB_TOKEN@gitlab.com/stevenguyen42/srmartketplacekey.git vihatbase_key
              cp -R vihatbase_key/env fastlane 
              cp -R vihatbase_key/file fastlane
              cp -R vihatbase_key/key . 
              rm -rf vihatbase_key
          - name: Set up code signing settings on Xcode project
            script: xcode-project use-profiles
          - name: Set up fastlane, notification, increase build number
            script: |
              sudo gem install fastlane
              gem install bundler
              bundle install
              fastlane increase_build_number_ios env:$ENV xcode:$XCODE_WORKSPACE
              fastlane start_build_telegram env:$ENV
          - name: Install npm dependencies
            script: |
              npm install
          - name: Install CocoaPods dependencies
            script: |
              cd ios && pod install
          - name: Set up code signing settings on Xcode project
            script: |
              xcode-project use-profiles --warn-only
          - name: Build ipa for distribution
            script: |
              xcode-project build-ipa \
                --workspace "$CM_BUILD_DIR/ios/$XCODE_WORKSPACE" \
                --scheme "$ENV"
              fastlane finish_build_telegram env:$ENV
        artifacts:
          - build/ios/ipa/*.ipa
          - /tmp/xcodebuild_logs/*.log
          - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
          - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
        publishing:
          email:
            recipients:
              - chaunn@vihatgroup.com
            notify:
              success: true
              failure: false
          app_store_connect:
            api_key: $APP_STORE_CONNECT_PRIVATE_KEY 
            key_id: $KEY_ID 
            issuer_id: $ISSUER_ID
            submit_to_testflight: true
            submit_to_app_store: false
