workflows:
    android-workflow:
      name: Android Workflow
      environment:
        android_signing:
          - keystore
        vars:
          PACKAGE_NAME: "com.vihat.marketplace.develop"
        groups:
          - google_play
      scripts:
        - name: Install npm dependencies
          script: | 
            npm install
        - name: Set Android SDK location
          script: | 
            echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"
        - name: Set up fastlane, notification, increase build number
          script: |
            sudo gem install fastlane
            gem install bundler
            bundle install
            fastlane increase_build_number_android env:develop
            fastlane start_build_telegram
        - name: Build Android release
          script: | 
            # LATEST_GOOGLE_PLAY_BUILD_NUMBER=$(google-play get-latest-build-number --package-name "$PACKAGE_NAME")
            # if [ -z $LATEST_GOOGLE_PLAY_BUILD_NUMBER ]; then
            #   # fallback in case no build number was found from Google Play.
            #   # Alternatively, you can `exit 1` to fail the build
            #   # BUILD_NUMBER is a Codemagic built-in variable tracking the number
            #   # of times this workflow has been built
            #     UPDATED_BUILD_NUMBER=$BUILD_NUMBER
            # else
            #     UPDATED_BUILD_NUMBER=$(($LATEST_GOOGLE_PLAY_BUILD_NUMBER + 1))
            # fi
            cd android
            ./gradlew assembleDevelopRelease
      artifacts:
          - android/app/build/outputs/**/*.apk
      publishing:
          script: |
            fastlane upload_distribution
